"""Create search analytics table with correct schema

Revision ID: 00449c6dd122
Revises: 14433ac3a9fb
Create Date: 2026-05-11 21:56:13.400575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00449c6dd122'
down_revision = '14433ac3a9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_search_analytics')
    with op.batch_alter_table('search_analytics', schema=None) as batch_op:
        batch_op.alter_column('search_query',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_search_query_date'))
        batch_op.create_index('idx_search_query_date', ['search_query', 'search_date'], unique=False)
        batch_op.drop_column('query')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_index('idx_search_query_date')
        batch_op.create_index(batch_op.f('idx_search_query_date'), ['query', 'search_date'], unique=False)
        batch_op.alter_column('search_query',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.create_table('_alembic_tmp_search_analytics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('search_date', sa.DATE(), nullable=True),
    sa.Column('search_count', sa.INTEGER(), nullable=True),
    sa.Column('result_count', sa.INTEGER(), nullable=True),
    sa.Column('avg_result_position', sa.FLOAT(), nullable=True),
    sa.Column('click_through_rate', sa.FLOAT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('search_query', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
