"""Add enhanced content management fields

Revision ID: 03b5cbf66121
Revises: 00449c6dd122
Create Date: 2026-05-11 22:26:02.092245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b5cbf66121'
down_revision = '00449c6dd122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_collaborator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_level', sa.String(length=20), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='unique_post_user_collaborator')
    )
    op.create_table('post_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('edited_by', sa.Integer(), nullable=False),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edited_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_save_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_saved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('version_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parent_post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_publish_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_scheduled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('engagement_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('search_rank', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('edit_permissions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'post', ['parent_post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_archived')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('edit_permissions')
        batch_op.drop_column('search_rank')
        batch_op.drop_column('engagement_score')
        batch_op.drop_column('view_count')
        batch_op.drop_column('is_scheduled')
        batch_op.drop_column('scheduled_publish_at')
        batch_op.drop_column('parent_post_id')
        batch_op.drop_column('version_number')
        batch_op.drop_column('last_saved_at')
        batch_op.drop_column('auto_save_data')
        batch_op.drop_column('is_draft')

    op.drop_table('post_version')
    op.drop_table('post_collaborator')
    # ### end Alembic commands ###
