"""Fix SearchAnalytics query field naming conflict

Revision ID: 14433ac3a9fb
Revises: 98fe66cbcd5e
Create Date: 2026-05-11 21:55:11.264247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14433ac3a9fb'
down_revision = '98fe66cbcd5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the new column as nullable
    with op.batch_alter_table('search_analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_query', sa.String(length=255), nullable=True))
    
    # Populate the new column with data from the old query field
    op.execute("UPDATE search_analytics SET search_query = query WHERE search_query IS NULL")
    
    # Now make the column NOT NULL and update indexes
    with op.batch_alter_table('search_analytics', schema=None) as batch_op:
        batch_op.alter_column('search_query', nullable=False)
        batch_op.drop_index(batch_op.f('idx_search_query_date'))
        batch_op.create_index('idx_search_query_date', ['search_query', 'search_date'], unique=False)
        batch_op.drop_column('query')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_index('idx_search_query_date')
        batch_op.create_index(batch_op.f('idx_search_query_date'), ['query', 'search_date'], unique=False)
        batch_op.drop_column('search_query')

    # ### end Alembic commands ###
