"""Initial migration with social login and session management

Revision ID: 91842caad752
Revises: 
Create Date: 2026-05-11 21:40:17.500385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91842caad752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('backup_codes_hash', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_2fa_used', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_2fa_used')
        batch_op.drop_column('backup_codes_hash')
        batch_op.drop_column('is_2fa_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
