"""Add search system models

Revision ID: 98fe66cbcd5e
Revises: 91842caad752
Create Date: 2026-05-11 21:53:37.072689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fe66cbcd5e'
down_revision = '91842caad752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('search_date', sa.Date(), nullable=True),
    sa.Column('search_count', sa.Integer(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('avg_result_position', sa.Float(), nullable=True),
    sa.Column('click_through_rate', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_analytics', schema=None) as batch_op:
        batch_op.create_index('idx_search_count', ['search_count'], unique=False)
        batch_op.create_index('idx_search_date', ['search_date'], unique=False)
        batch_op.create_index('idx_search_query_date', ['query', 'search_date'], unique=False)

    op.create_table('search_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('indexed_content', sa.Text(), nullable=True),
    sa.Column('search_vector', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('vote_score', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_index', schema=None) as batch_op:
        batch_op.create_index('idx_search_author', ['author_id'], unique=False)
        batch_op.create_index('idx_search_category', ['category_id'], unique=False)
        batch_op.create_index('idx_search_content', ['content_type', 'content_id'], unique=False)
        batch_op.create_index('idx_search_created', ['created_at'], unique=False)
        batch_op.create_index('idx_search_relevance', ['relevance_score'], unique=False)

    op.create_table('user_search_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('results_per_page', sa.Integer(), nullable=True),
    sa.Column('default_sort', sa.String(length=20), nullable=True),
    sa.Column('default_order', sa.String(length=10), nullable=True),
    sa.Column('include_comments', sa.Boolean(), nullable=True),
    sa.Column('include_users', sa.Boolean(), nullable=True),
    sa.Column('enable_highlights', sa.Boolean(), nullable=True),
    sa.Column('show_suggestions', sa.Boolean(), nullable=True),
    sa.Column('auto_apply_filters', sa.Boolean(), nullable=True),
    sa.Column('remember_filters', sa.Boolean(), nullable=True),
    sa.Column('save_search_history', sa.Boolean(), nullable=True),
    sa.Column('anonymous_search', sa.Boolean(), nullable=True),
    sa.Column('search_scope', sa.String(length=20), nullable=True),
    sa.Column('time_filter', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('min_quality', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_search_preferences', schema=None) as batch_op:
        batch_op.create_index('idx_search_prefs_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_search_preferences', schema=None) as batch_op:
        batch_op.drop_index('idx_search_prefs_user')

    op.drop_table('user_search_preferences')
    with op.batch_alter_table('search_index', schema=None) as batch_op:
        batch_op.drop_index('idx_search_relevance')
        batch_op.drop_index('idx_search_created')
        batch_op.drop_index('idx_search_content')
        batch_op.drop_index('idx_search_category')
        batch_op.drop_index('idx_search_author')

    op.drop_table('search_index')
    with op.batch_alter_table('search_analytics', schema=None) as batch_op:
        batch_op.drop_index('idx_search_query_date')
        batch_op.drop_index('idx_search_date')
        batch_op.drop_index('idx_search_count')

    op.drop_table('search_analytics')
    # ### end Alembic commands ###
